added ng client
theeye-io-team/sync-tasks pull request #2
Opened 2022-01-28 20:02 UTC by damian-theeye

2022-01-28 20:27 UTC, facugon requested changes

2022-01-28 20:27 UTC, facugon commented on client/src/app/api/session/session.service.ts
> +	getLoginData = async (email:string, password:string, customer:string | null):Promise<any> => {
```suggestion
	getLoginData =  (email:string, password:string, customer:string | null):Promise<any> => {
```

2022-01-28 20:27 UTC, facugon commented on client/src/app/api/session/session.service.ts
> +		})
we should avoid using return new Promise in this function.

if the code is not using any method that process async code using callbacks , then don't use new Promise
just call the function using await and return the desired value

on error just throw new Error and the calling function just take care of it
or keep the try / catch if need

2022-01-28 20:43 UTC, facugon requested changes

2022-01-28 20:43 UTC, facugon commented on client/src/app/api/session/session.service.ts
> +		})
I think  login and getLoginData can be joined

2022-01-28 20:43 UTC, facugon commented on client/src/app/login-screen/login-screen.component.ts
> +			if(e.status === 50) {
```suggestion
			if(e.status === 500) {
```

2022-01-28 20:43 UTC, facugon commented on client/src/app/login-screen/login-screen.component.ts
> +			if(e.status === 404) {
I believe this escenario is not possible in this case...

2022-01-28 20:43 UTC, facugon commented on client/src/app/main-screen/main-screen.component.ts
> +	getTaskResult = async ():Promise<any> => {
```suggestion
	getTaskResult =  ():Promise<any> => {
```

2022-01-28 20:43 UTC, facugon commented on client/src/app/main-screen/main-screen.component.ts
> +	}
in general reactive actions are not required to be "async/await"-ables
actions in most cases are performed async and events will tell you **when** are accomplished 

I believe this can be written as follow 

```suggestion
	taskResultButton = () => {
		this.getTaskResult().then(response => {
			this.taskResultRaw = response
			this.setResultVars(response)
			this.prettifyResult(response)
			this.showOverlay = false
		}).catch( e => {
			this.taskResultRaw = e
			this.setResultVars(e.error)
			this.prettifyResult(e)
			this.showOverlay = false
		})
	}
```

if you are not returning any value , and the outer function is not waiting the result (I'm guessing the scenario) , then you don't need async functions here

2022-01-28 20:46 UTC, facugon commented
I'm seeing a lot of this

```javascript
	funcName = **async**():Promise<any> => {
             return new Promise ( (res, rej) => { 
                 something( (err,  data) => {
                      if (err) { rej(err) }
                      else { res(data) }
                 })
             } )
        }

```
and is not correct. is not async if you are returning a promise

2022-02-15 22:51 UTC, damian-theeye commented
please check my changes, and merge if you so desire my good sir

2022-04-13 20:30 UTC, merged